-- Users: (id from 1000)
INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1000, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1001, 0, 'teszt.peter', 'petike@gmail.com', '12345', 'USER');

-- Vehicles: (id from 2000)
INSERT INTO VEHICLES(ID, VERSION, COST_PER_DAY, LICENSE_PLATE_NR, MANUFACTURE_DATE, MANUFACTURER, TYPE) VALUES (2000, 0, 15000, 'ASD123', 2012, 'Ford', 'Mustang');
INSERT INTO VEHICLES(ID, VERSION, COST_PER_DAY, LICENSE_PLATE_NR, MANUFACTURE_DATE, MANUFACTURER, TYPE) VALUES (2001, 0, 3000, 'SUZ111', 2010, 'Suzuki', 'Swift');

-- Rentings: (id auto incrementing from 0)
INSERT INTO RENTINGS(ID, VERSION, START_DATE, END_DATE, USER_ID, VEHICLE_ID) VALUES (HIBERNATE_SEQUENCE.nextVal, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1000, 2000);
INSERT INTO RENTINGS(ID, VERSION, START_DATE, END_DATE, USER_ID, VEHICLE_ID) VALUES (HIBERNATE_SEQUENCE.nextVal, 0, CURRENT_TIMESTAMP, null, 1001, 2001);
